--wf-tcp=80,443,2053,2083,2087,2096,8443,5222,5223,19716 --wf-udp=443,3478-3480,50000-50100,4500
--filter-tcp=2053,2083,2087,2096,8443 --hostlist="lists\discord.txt" --dpi-desync=fake --dpi-desync-repeats=3 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=1500000 --new
--filter-udp=3478-3480,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-repeats=3 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=1200000 --new
--filter-tcp=443 --hostlist="lists\discord.txt" --dpi-desync=multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 --dpi-desync-split-seqovl-pattern="bin\tls_clienthello_www_google_com.bin" --new
--filter-udp=443 --hostlist="lists\discord.txt" --dpi-desync=fake --dpi-desync-repeats=3 --dpi-desync-fake-quic="bin\quic_initial_www_google_com.bin" --new
--filter-tcp=80 --hostlist="lists\discord.txt" --dpi-desync=fake,multisplit --dpi-desync-split-pos=1 --new
--filter-tcp=80 --hostlist="lists\youtube_twitch.txt" --dpi-desync=multisplit --dpi-desync-split-pos=1 --new
--filter-tcp=443 --hostlist="lists\youtube_twitch.txt" --dpi-desync=multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1,midsld --dpi-desync-split-seqovl-pattern="bin\tls_clienthello_www_google_com.bin" --new
--filter-udp=443 --hostlist="lists\youtube_twitch.txt" --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-fake-quic="bin\quic_initial_www_google_com.bin" --new
--filter-tcp=80 --hostlist="lists\black-list.txt" --hostlist-exclude="lists\white-list.txt" --ipset="lists\ipset-global.txt" --dpi-desync=multisplit --dpi-desync-split-pos=1 --new
--filter-tcp=443 --hostlist="lists\black-list.txt" --hostlist-exclude="lists\white-list.txt" --ipset="lists\ipset-global.txt" --dpi-desync=multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1,midsld --dpi-desync-split-seqovl-pattern="bin\tls_clienthello_www_google_com.bin" --new
--filter-udp=443 --hostlist="lists\black-list.txt" --hostlist-exclude="lists\white-list.txt" --ipset="lists\ipset-global.txt" --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-fake-quic="bin\quic_initial_www_google_com.bin" --new
--filter-tcp=5222,5223,19716 --ipset="lists\ipset-global.txt" --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=1000000 --new
--filter-udp=4500 --ipset="lists\ipset-global.txt" --dpi-desync=fake --dpi-desync-repeats=2 --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=800000 --new